default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fb_clone_app_development

test:
  <<: *default
  database: fb_clone_app_test

production:
  <<: *default
  database: fb_clone_app_production
  username: fb_clone_app
  password: <%= ENV['FB_CLONE_APP_DATABASE_PASSWORD'] %>
